[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/adjust/rmq"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.1"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.0.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.3.0"
